import { int, mysqlEnum, mysqlTable, text, timestamp, varchar, float, boolean, json } from "drizzle-orm/mysql-core";

// ===== Users テーブル（拡張） =====
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  school: varchar("school", { length: 255 }),
  grade: varchar("grade", { length: 64 }),
  bio: text("bio"),
  avatarUrl: text("avatarUrl"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

// ===== Activities テーブル =====
export const activities = mysqlTable("activities", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  type: mysqlEnum("type", ["text", "audio", "image"]).notNull(),
  content: text("content"),
  mediaUrl: text("mediaUrl"),
  mediaKey: varchar("mediaKey", { length: 512 }),
  transcription: text("transcription"),
  category: varchar("category", { length: 128 }),
  aiSummary: text("aiSummary"),
  aiProcessed: boolean("aiProcessed").default(false).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

// ===== Extracted_Insights テーブル =====
export const extractedInsights = mysqlTable("extracted_insights", {
  id: int("id").autoincrement().primaryKey(),
  activityId: int("activityId").notNull(),
  userId: int("userId").notNull(),
  type: mysqlEnum("type", ["skill", "interest", "experience", "achievement", "goal"]).notNull(),
  label: varchar("label", { length: 255 }).notNull(),
  confidence: float("confidence").default(0.5),
  context: text("context"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

// ===== Profiles テーブル =====
export const profiles = mysqlTable("profiles", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  generatedBio: text("generatedBio"),
  skills: json("skills"),
  interests: json("interests"),
  experiences: json("experiences"),
  strengths: json("strengths"),
  personalityTraits: json("personalityTraits"),
  lastGeneratedAt: timestamp("lastGeneratedAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

// ===== Tasks テーブル =====
export const tasks = mysqlTable("tasks", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  title: varchar("title", { length: 500 }).notNull(),
  description: text("description"),
  status: mysqlEnum("status", ["pending", "in_progress", "completed", "cancelled"]).default("pending").notNull(),
  priority: mysqlEnum("priority", ["low", "medium", "high"]).default("medium").notNull(),
  dueDate: timestamp("dueDate"),
  sourceActivityId: int("sourceActivityId"),
  isAutoGenerated: boolean("isAutoGenerated").default(false).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

// ===== Connections テーブル =====
export const connections = mysqlTable("connections", {
  id: int("id").autoincrement().primaryKey(),
  userId1: int("userId1").notNull(),
  userId2: int("userId2").notNull(),
  status: mysqlEnum("status", ["pending", "accepted", "rejected", "blocked"]).default("pending").notNull(),
  matchedReason: text("matchedReason"),
  compatibilityScore: float("compatibilityScore"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

// ===== Match_Recommendations テーブル =====
export const matchRecommendations = mysqlTable("match_recommendations", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  targetUserId: int("targetUserId").notNull(),
  type: mysqlEnum("type", ["friend", "romantic", "career", "role_model"]).notNull(),
  score: float("score").notNull(),
  reasons: json("reasons"),
  isViewed: boolean("isViewed").default(false).notNull(),
  isActedUpon: boolean("isActedUpon").default(false).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

// Type exports
export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;
export type Activity = typeof activities.$inferSelect;
export type InsertActivity = typeof activities.$inferInsert;
export type ExtractedInsight = typeof extractedInsights.$inferSelect;
export type InsertExtractedInsight = typeof extractedInsights.$inferInsert;
export type Profile = typeof profiles.$inferSelect;
export type InsertProfile = typeof profiles.$inferInsert;
export type Task = typeof tasks.$inferSelect;
export type InsertTask = typeof tasks.$inferInsert;
export type Connection = typeof connections.$inferSelect;
export type InsertConnection = typeof connections.$inferInsert;
export type MatchRecommendation = typeof matchRecommendations.$inferSelect;
export type InsertMatchRecommendation = typeof matchRecommendations.$inferInsert;
